[package]
name = "rust_cli_mysql"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "20.0"
dotenv = "0.15"
#serde = { version = "1.0", features = ["derive"] }
#serde_with = { version = "1.14.0", features = ["chrono"] }
#chrono = "0.4"
